[package]
name = "rustourent"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_bencode = "0.2.3"
serde = "^1.0.0"
serde_derive = "^1.0.0"
